version: "3.8"

services:
  backend:
    container_name: matchpoint-backend
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    env_file:
      - ./BackEnd/.env
    restart: always
    networks:
      - matchpoint-network

  frontend:
    container_name: matchpoint-frontend
    build:
      context: ./FrontEnd
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
    networks:
      - matchpoint-network

networks:
  matchpoint-network:
    driver: bridge
