version: '3.8'

services:
  backend:
    build: ./BackEnd
    env_file: ./BackEnd/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./FrontEnd
    env_file: ./FrontEnd/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend