version: "3.8"

services:
  backend:
    container_name: matchpoint-backend
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    env_file:
      - ./BackEnd/.env
    restart: always
    networks:
      - matchpoint-network

  frontend:
    container_name: matchpoint-frontend
    build:
      context: ./FrontEnd
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_SERVER_URL=${VITE_SERVER_URL}
        - VITE_GOOGLE_REDIRECT_URI=${VITE_GOOGLE_REDIRECT_URI}
        - VITE_FACEBOOK_APP_ID=${VITE_FACEBOOK_APP_ID}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always
    networks:
      - matchpoint-network

networks:
  matchpoint-network:
    driver: bridge
